#!/bin/bash
set -eu

#Source the setup file to initialize variables
source ../00_Setup_Pipeline/01_Pipeline_Setup.sh

#Check that each variable prints a value to the terminal:
echo "-----------------------"
echo "Start of variable list:"
echo "-----------------------"
echo "SCRIPT_DIR:"
echo ${SCRIPT_DIR}
echo "Dataset_Label:"
echo ${Dataset_Label}
echo "BU_User:"
echo ${BU_User}
echo "VM_DIR_UCSC:"
echo ${VM_DIR_UCSC}
echo "-----------------------"
echo "End of variable list"
echo "-----------------------"

#A text file (Sample_Labels.txt) is needed to run this script
SCRIPT_DIR=$(pwd)
cp $Sample_Labels_DIR/Sample_Labels.txt $SCRIPT_DIR

#Output dir to store text files:
OUTPUT_DIR="${SCRIPT_DIR}/${Dataset_Label}_UCSC_Track_Lines"
###############################
if [ ! -d ${OUTPUT_DIR} ]; then
    mkdir -p ${OUTPUT_DIR}
else
    rm ${OUTPUT_DIR}/*.txt
fi
###############################

cd ${SCRIPT_DIR}
OUTPUT_FILE_PileUp=${OUTPUT_DIR}/${Dataset_Label}'_Tracks_PileUp.txt'

if [ -f ${OUTPUT_FILE_PileUp} ]; then
    rm ${OUTPUT_FILE_PileUp}; 
fi

echo 'Start *_Tracks_PileUp.txt'

#Add TAD regions track line (generated by Bryan):

echo "track type=bigBed name=TADS_ABv4 description=Liver_TADs visibility=pack itemRgb=On bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/TADS_ABv4.bb" >> ${OUTPUT_FILE_PileUp}
echo "track type=bigBed name=F_14_segments_recolored description=UT_Female_Chromatin_Map visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/F_14_segments_recolored.bb" >> ${OUTPUT_FILE_PileUp}
echo "track type=bigBed name=M_14_segments_recolored description=UT_Male_Chromatin_Map visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/M_14_segments_recolored.bb" >> ${OUTPUT_FILE_PileUp}
echo "track type=bigBed name=mm9-blacklist description=ENCODE_mm9-blacklist visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/mm9-blacklist.bb" >> ${OUTPUT_FILE_PileUp}

## Add diffReps tracks
if [ -f "../11_DiffReps_Summary/Job_Summary/all_diffreps_ucsc_tracks.txt" ]; then
   cat ../11_DiffReps_Summary/Job_Summary/all_diffreps_ucsc_tracks.txt >> ${OUTPUT_FILE_PileUp}
fi

echo 'End chromatin state tracks'
echo 'Add BAM and BigWig file tracks'

#Text file has a header line to ignore:
tail -n +2 Sample_Labels.txt > Sample_Labels.temp
#Use a while loop to run jobs
while IFS=$'\t' read -r -a myArray
do

    Sample_DIR=${myArray[0]}
    Sample_ID=${myArray[1]}
    Description=${myArray[2]}
    Color=${myArray[3]}
    BW_Visual=hide

    echo 'track type=bigWig name="'${Sample_ID}'_RiPPM_norm" description="'${Description}'" db=mm9 visibility='${BW_Visual}' autoScale=on viewLimits=0.0:100.0 color="'${Color}'" yLineOnOff=off windowingFunction=mean smoothingWindow=3 maxHeightPixels=100:64:8 bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Sample_ID}'_RiPPM_norm.bw'

    #macs2:
    echo "track type=bigBed name=\"${Description}_MACS2_narrow\" description=\"${Description}_MACS2_narrow\" visibility=squish color=0,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/${BU_User}/${Dataset_Label}/${Sample_ID}_narrow_MACS2_peaks.narrowPeak.bb"
    echo "track type=bigBed name=\"${Description}_MACS2_broad\" description=\"${Description}_MACS2_broad\" visibility=squish color=255,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/${BU_User}/${Dataset_Label}/${Sample_ID}_broad_MACS2_peaks.broadPeak.bb"

    #SICER:
    if [ -d "${Dataset_DIR}/${Sample_ID}/fastq/bowtie2/${Sample_ID}_SICER_output" ]
    then
	cd ${Dataset_DIR}/${Sample_ID}/fastq/bowtie2/${Sample_ID}'_SICER_output'
	#General way to refer to the main output file
	Peaks_Called_File=$(ls *.bb)
	echo 'track type=bigBed name="'${Sample_ID}'_SICER" description="'${Sample_ID}'_SICER" visibility=hide color=0,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Peaks_Called_File}
	cd ${SCRIPT_DIR}
    fi

    BAM_Visual=squish
    echo 'track type=bam name="'${Sample_ID}'_'${Description}'" description="'${Sample_ID}'_'${Description}'" bamColorMode=strand db=mm9 visibility='${BAM_Visual}' bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Sample_ID}'_sorted_mapped.bam'
done < Sample_Labels.temp >> ${OUTPUT_FILE_PileUp}
echo 'End *_Tracks_PileUp.txt'



OUTPUT_FILE_Wiggle=${OUTPUT_DIR}/${Dataset_Label}'_Tracks_Wiggle.txt'

if [ -f ${OUTPUT_FILE_Wiggle} ]; then
    rm ${OUTPUT_FILE_Wiggle}; 
fi

echo 'Start *_Tracks_Wiggle.txt'

echo "track type=bigBed name=TADS_ABv4 description=Liver_TADs visibility=pack itemRgb=On bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/TADS_ABv4.bb" >> ${OUTPUT_FILE_Wiggle}
echo "track type=bigBed name=F_14_segments_recolored description=UT_Female_Chromatin_Map visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/F_14_segments_recolored.bb" >> ${OUTPUT_FILE_Wiggle}
echo "track type=bigBed name=M_14_segments_recolored description=UT_Male_Chromatin_Map visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/M_14_segments_recolored.bb" >> ${OUTPUT_FILE_Wiggle}
echo "track type=bigBed name=mm9-blacklist description=ENCODE_mm9-blacklist visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/mm9-blacklist.bb" >> ${OUTPUT_FILE_Wiggle}

## Add diffReps tracks
if [ -f "../11_DiffReps_Summary/Job_Summary/all_diffreps_ucsc_tracks.txt" ]; then
   cat ../11_DiffReps_Summary/Job_Summary/all_diffreps_ucsc_tracks.txt >> ${OUTPUT_FILE_Wiggle}
fi

echo 'End chromatin state tracks'
echo 'Add BAM and BigWig file tracks'

#Text file has a header line to ignore:
tail -n +2 Sample_Labels.txt > Sample_Labels.temp
#Use a while loop to run jobs
while IFS=$'\t' read -r -a myArray
do
    Sample_DIR=${myArray[0]}
    Sample_ID=${myArray[1]}
    Description=${myArray[2]}
    Color=${myArray[3]}
    BW_Visual=full

    echo 'track type=bigWig name="'${Sample_ID}'_RiPPM_norm" description="'${Description}'" db=mm9 visibility='${BW_Visual}' autoScale=off viewLimits=0.0:100.0 color="'${Color}'" yLineOnOff=off windowingFunction=mean smoothingWindow=3 maxHeightPixels=100:64:8 bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Sample_ID}'_RiPPM_norm.bw'

    #Make bigBed tracks (peaks):
    #macs2:
    echo "track type=bigBed name=\"${Description}_MACS2_narrow\" description=\"${Description}_MACS2_narrow\" visibility=squish color=0,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/${BU_User}/${Dataset_Label}/${Sample_ID}_narrow_MACS2_peaks.narrowPeak.bb"
    echo "track type=bigBed name=\"${Description}_MACS2_broad\" description=\"${Description}_MACS2_broad\" visibility=squish color=255,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/${BU_User}/${Dataset_Label}/${Sample_ID}_broad_MACS2_peaks.broadPeak.bb"

    #SICER:

    if [ -d "${Dataset_DIR}/${Sample_ID}/fastq/bowtie2/${Sample_ID}_SICER_output" ]
    then

	cd ${Dataset_DIR}/${Sample_ID}/fastq/bowtie2/${Sample_ID}'_SICER_output'
	#General way to refer to the main output file
	Peaks_Called_File=$(ls *.bb)
	echo 'track type=bigBed name="'${Sample_ID}'_SICER" description="'${Sample_ID}'_SICER" visibility=hide color=0,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Peaks_Called_File}
	cd ${SCRIPT_DIR}
    fi

    BAM_Visual=hide

    echo 'track type=bam name="'${Sample_ID}'_'${Description}'" description="'${Sample_ID}'_'${Description}'" bamColorMode=strand db=mm9 visibility='${BAM_Visual}' bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Sample_ID}'_sorted_mapped.bam'
done < Sample_Labels.temp >> ${OUTPUT_FILE_Wiggle}
echo
echo 'End *_Tracks_Wiggle.txt'
echo
##################################################################################
OUTPUT_FILE_Wiggle_autoON=${OUTPUT_DIR}/${Dataset_Label}'_Tracks_Wiggle_autoON.txt'

if [ -f ${OUTPUT_FILE_Wiggle_autoON} ]; then
    rm ${OUTPUT_FILE_Wiggle_autoON}; 
fi

echo
echo 'Start *_Tracks_Wiggle_autoON.txt'
echo

#Add TAD regions track line (generated by Bryan):
echo "track type=bigBed name=TADS_ABv4 description=Liver_TADs visibility=pack itemRgb=On bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/TADS_ABv4.bb" >> ${OUTPUT_FILE_Wiggle_autoON}
echo "track type=bigBed name=F_14_segments_recolored description=UT_Female_Chromatin_Map visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/F_14_segments_recolored.bb" >> ${OUTPUT_FILE_Wiggle_autoON}
echo "track type=bigBed name=M_14_segments_recolored description=UT_Male_Chromatin_Map visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/M_14_segments_recolored.bb" >> ${OUTPUT_FILE_Wiggle_autoON}
echo "track type=bigBed name=mm9-blacklist description=ENCODE_mm9-blacklist visibility=dense itemRgb=on bigDataUrl=http://waxmanlabvm.bu.edu/aramp10/Lab_Files/mm9-blacklist.bb" >> ${OUTPUT_FILE_Wiggle_autoON}

## Add diffReps tracks
if [ -f "../11_DiffReps_Summary/Job_Summary/all_diffreps_ucsc_tracks.txt" ]; then
   cat ../11_DiffReps_Summary/Job_Summary/all_diffreps_ucsc_tracks.txt >> ${OUTPUT_FILE_Wiggle_autoON}
fi

echo 'End chromatin state tracks'
echo 'Add BAM and BigWig file tracks'

tail -n +2 Sample_Labels.txt > Sample_Labels.temp
while IFS=$'\t' read -r -a myArray
do

    Sample_DIR=${myArray[0]}
    Sample_ID=${myArray[1]}
    Description=${myArray[2]}
    Color=${myArray[3]}
    BW_Visual=full

    echo 'track type=bigWig name="'${Sample_ID}'_RiPPM_norm" description="'${Description}'" db=mm9 visibility='${BW_Visual}' autoScale=on viewLimits=0.0:100.0 color="'${Color}'" yLineOnOff=off windowingFunction=mean smoothingWindow=3 maxHeightPixels=100:64:8 bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Sample_ID}'_RiPPM_norm.bw'

    #macs2:
    echo "track type=bigBed name=\"${Description}_MACS2_narrow\" description=\"${Description}_MACS2_narrow\" visibility=squish color=0,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/${BU_User}/${Dataset_Label}/${Sample_ID}_narrow_MACS2_peaks.narrowPeak.bb"
    echo "track type=bigBed name=\"${Description}_MACS2_broad\" description=\"${Description}_MACS2_broad\" visibility=squish color=255,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/${BU_User}/${Dataset_Label}/${Sample_ID}_broad_MACS2_peaks.broadPeak.bb"

    #SICER:
    if [ -d "${Dataset_DIR}/${Sample_ID}/fastq/bowtie2/${Sample_ID}_SICER_output" ]
    then
	cd ${Dataset_DIR}/${Sample_ID}/fastq/bowtie2/${Sample_ID}'_SICER_output'
	#General way to refer to the main output file
	Peaks_Called_File=$(ls *.bb)
	echo 'track type=bigBed name="'${Sample_ID}'_SICER" description="'${Sample_ID}'_SICER" visibility=hide color=0,0,0 bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Peaks_Called_File}
	cd ${SCRIPT_DIR}
    fi


    BAM_Visual=hide

    echo 'track type=bam name="'${Sample_ID}'_'${Description}'" description="'${Sample_ID}'_'${Description}'" bamColorMode=strand db=mm9 visibility='${BAM_Visual}' bigDataUrl=http://waxmanlabvm.bu.edu/'${BU_User}'/'${Dataset_Label}'/'${Sample_ID}'_sorted_mapped.bam'
done < Sample_Labels.temp >> ${OUTPUT_FILE_Wiggle_autoON}

echo 'End *_Tracks_Wiggle_autoON.txt'

rm *.temp
echo '#---------------------------------------------------------------------------'
echo 'Check out '${OUTPUT_FILE_PileUp}
echo 'Check out '${OUTPUT_FILE_Wiggle}
echo 'Check out '${OUTPUT_FILE_Wiggle_autoON}
echo '#---------------------------------------------------------------------------'

# cp -a ${OUTPUT_DIR} ${VM_DIR_UCSC}/
